"""
push.py — Web Push (VAPID) for Josephine's proactive "moments".

Sends a browser/OS notification (works on Chrome/Android + desktop; on iOS only
to an installed home-screen PWA, iOS 16.4+). Subscriptions are stored locally;
content for the daily nudge comes from the Living Almanac.

Fully guarded: if VAPID keys aren't configured, push is simply disabled and every
function degrades to a no-op — nothing breaks.

Setup (dev keys already generated by the team; for prod set env):
  VAPID_PUBLIC_KEY  = application server key (base64url)
  VAPID_PRIVATE_KEY = PKCS8 PEM (or a path to vapid_private.pem)
  VAPID_SUBJECT     = mailto:you@example.com
"""
import os
import json
import time

_DIR = os.path.dirname(os.path.abspath(__file__))
_SUBS_PATH = os.path.join(_DIR, 'data', 'push_subscriptions.json')
_SUBJECT = os.environ.get('VAPID_SUBJECT', 'mailto:hello@josephine.app')

try:
    from pywebpush import webpush, WebPushException
    _HAVE_LIB = True
except Exception:  # noqa: BLE001
    _HAVE_LIB = False


def _load_public():
    v = os.environ.get('VAPID_PUBLIC_KEY')
    if v:
        return v.strip()
    p = os.path.join(_DIR, 'vapid_public.txt')
    if os.path.exists(p):
        return open(p).read().strip()
    return None


def _load_private():
    """Return the VAPID private key as a PEM string (pywebpush accepts PEM)."""
    v = os.environ.get('VAPID_PRIVATE_KEY')
    if v and 'BEGIN' in v:
        return v
    if v and os.path.exists(v):
        return open(v).read()
    p = os.path.join(_DIR, 'vapid_private.pem')
    if os.path.exists(p):
        return open(p).read()
    return None


_PUBLIC = _load_public()
_PRIVATE = _load_private()


def is_enabled():
    return bool(_HAVE_LIB and _PUBLIC and _PRIVATE)


def public_key():
    return _PUBLIC


# ── subscription store ───────────────────────────────────────────────────────
def _read_subs():
    try:
        with open(_SUBS_PATH) as f:
            return json.load(f)
    except Exception:  # noqa: BLE001
        return []


def _write_subs(subs):
    try:
        os.makedirs(os.path.dirname(_SUBS_PATH), exist_ok=True)
        with open(_SUBS_PATH, 'w') as f:
            json.dump(subs, f)
    except Exception as e:  # noqa: BLE001
        print(f'[push] could not persist subscriptions: {e}')


def add_subscription(sub, lang='en', email=None):
    """Store a PushSubscription (dedup by endpoint). An optional `email` ties the
    subscription to a signed-in user so personalised pushes (Phase 17B) can
    target one person. Returns True on success."""
    try:
        endpoint = (sub or {}).get('endpoint')
        if not endpoint:
            return False
        subs = _read_subs()
        subs = [s for s in subs if s.get('sub', {}).get('endpoint') != endpoint]
        entry = {'sub': sub, 'lang': (lang or 'en')[:2], 'at': int(time.time())}
        if email:
            entry['email'] = email
        subs.append(entry)
        _write_subs(subs)
        return True
    except Exception as e:  # noqa: BLE001
        print(f'[push] add_subscription failed: {e}')
        return False


def subscriptions_for(email):
    """All stored subscription entries belonging to one user email."""
    return [s for s in _read_subs() if s.get('email') == email]


def remove_subscription(endpoint):
    subs = [s for s in _read_subs() if s.get('sub', {}).get('endpoint') != endpoint]
    _write_subs(subs)


def subscription_count():
    return len(_read_subs())


# ── sending ──────────────────────────────────────────────────────────────────
def _send_one(sub, payload):
    webpush(
        subscription_info=sub,
        data=json.dumps(payload),
        vapid_private_key=_PRIVATE,
        vapid_claims={'sub': _SUBJECT},
        timeout=10,
    )


def send_to_all(title, body, url='/', icon='/josephine/portrait.png', lang=None):
    """Send a notification to every subscriber (optionally filtered by lang).
    Prunes dead subscriptions (410/404). Returns {sent, failed}. Guarded."""
    if not is_enabled():
        return {'sent': 0, 'failed': 0, 'disabled': True}
    subs = _read_subs()
    payload = {'title': title, 'body': body, 'url': url, 'icon': icon}
    sent, dead = 0, []
    for entry in subs:
        if lang and entry.get('lang') != lang:
            continue
        try:
            _send_one(entry['sub'], payload)
            sent += 1
        except WebPushException as e:  # noqa: BLE001
            code = getattr(getattr(e, 'response', None), 'status_code', None)
            if code in (404, 410):
                dead.append(entry['sub'].get('endpoint'))
            else:
                print(f'[push] send error: {e}')
        except Exception as e:  # noqa: BLE001
            print(f'[push] send error: {e}')
    if dead:
        remaining = [s for s in subs if s.get('sub', {}).get('endpoint') not in dead]
        _write_subs(remaining)
    return {'sent': sent, 'failed': len(dead)}


def send_to_user(email, title, body, url='/', icon='/josephine/portrait.png'):
    """Send a notification to every device a single user has subscribed (Phase
    17B personalised push). Prunes dead subscriptions. Returns {sent, failed}."""
    if not is_enabled():
        return {'sent': 0, 'failed': 0, 'disabled': True}
    mine = subscriptions_for(email)
    if not mine:
        return {'sent': 0, 'failed': 0, 'no_subscription': True}
    payload = {'title': title, 'body': body, 'url': url, 'icon': icon}
    sent, dead = 0, []
    for entry in mine:
        try:
            _send_one(entry['sub'], payload)
            sent += 1
        except WebPushException as e:  # noqa: BLE001
            code = getattr(getattr(e, 'response', None), 'status_code', None)
            if code in (404, 410):
                dead.append(entry['sub'].get('endpoint'))
            else:
                print(f'[push] send_to_user error: {e}')
        except Exception as e:  # noqa: BLE001
            print(f'[push] send_to_user error: {e}')
    if dead:
        subs = [s for s in _read_subs() if s.get('sub', {}).get('endpoint') not in dead]
        _write_subs(subs)
    return {'sent': sent, 'failed': len(dead)}
